# Generated by Django 5.2.5 on 2026-03-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.TextField()),
                ('identifier', models.TextField(blank=True, null=True)),
                ('role', models.CharField(default='student', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_username', models.CharField(max_length=100)),
                ('owner_name', models.TextField()),
                ('plate_number', models.TextField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('sticker_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
