# Generated by Django 5.2.5 on 2026-03-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleapplication',
            name='is_seen',
            field=models.BooleanField(default=True),
        ),
    ]
